package ddog.domain.payment.enums;

public enum ReservationStatus {
    PENDING,
    DEPOSIT_PAID,
    USER_CANCELLED,
    PROVIDER_CANCELLED_NO_REFUND,
    SYSTEM_CANCELLED_NO_REFUND,
    CANCELLED_NO_SHOW_NO_REFUND,

    PROVIDER_CANCELLED_REFUNDED,
    SYSTEM_CANCELLED_REFUNDED,
    CANCELLED_NO_SHOW_REFUNDED,

    SERVICE_COMPLETED,
}
